
[appendix]
== Frequently Asked Questions


'''
**How do I test my Hazelcast cluster?**

Hazelcast allows you to create more than one instance on the same JVM.
Each member is called `HazelcastInstance` and each has its own configuration,
socket and threads, so you can treat them as totally separate instances.

This enables you to write and to run cluster unit tests on a single JVM.
Because you can use this feature for creating separate members different applications running on
the same JVM (imagine running multiple web applications on the same JVM),
you can also use this feature for testing your Hazelcast cluster.

Let's say you want to test if two members have the same size of a map.

[source,java]
----
@Test
public void testTwoMemberMapSizes() {
  // start the first member
  HazelcastInstance h1 = Hazelcast.newHazelcastInstance();
  // get the map and put 1000 entries
  Map map1 = h1.getMap( "testmap" );
  for ( int i = 0; i < 1000; i++ ) {
    map1.put( i, "value" + i );
  }
  // check the map size
  assertEquals( 1000, map1.size() );
  // start the second member
  HazelcastInstance h2 = Hazelcast.newHazelcastInstance();
  // get the same map from the second member
  Map map2 = h2.getMap( "testmap" );
  // check the size of map2
  assertEquals( 1000, map2.size() );
  // check the size of map1 again
  assertEquals( 1000, map1.size() );
}
----

In the test above, everything happens in the same thread.
When developing a multi-threaded test, you need to carefully handle coordination of the thread executions.
It is highly recommended that you use `CountDownLatch` for thread coordination (you can certainly use other ways).
Here is an example where we need to listen for messages and make sure that we got these messages.

[source,java]
----
@Test
public void testTopic() {
  // start two member cluster
  HazelcastInstance h1 = Hazelcast.newHazelcastInstance();
  HazelcastInstance h2 = Hazelcast.newHazelcastInstance();
  String topicName = "TestMessages";
  // get a topic from the first member and add a messageListener
  ITopic<String> topic1 = h1.getTopic( topicName );
  final CountDownLatch latch1 = new CountDownLatch( 1 );
  topic1.addMessageListener( new MessageListener() {
    public void onMessage( Object msg ) {
      assertEquals( "Test1", msg );
      latch1.countDown();
    }
  });
  // get a topic from the second member and add a messageListener
  ITopic<String> topic2 = h2.getTopic(topicName);
  final CountDownLatch latch2 = new CountDownLatch( 2 );
  topic2.addMessageListener( new MessageListener() {
    public void onMessage( Object msg ) {
      assertEquals( "Test1", msg );
      latch2.countDown();
    }
  } );
  // publish the first message, both should receive this
  topic1.publish( "Test1" );
  // shutdown the first member
  h1.shutdown();
  // publish the second message, second member's topic should receive this
  topic2.publish( "Test1" );
  try {
    // assert that the first member's topic got the message
    assertTrue( latch1.await( 5, TimeUnit.SECONDS ) );
    // assert that the second members' topic got two messages
    assertTrue( latch2.await( 5, TimeUnit.SECONDS ) );
  } catch ( InterruptedException ignored ) {
  }
}
----

You can start Hazelcast members with different configurations.
Remember to call `Hazelcast.shutdownAll()` after each test case to make sure that
there is no other running member left from the previous tests.

[source,java]
----
@After
public void cleanup() throws Exception {
  Hazelcast.shutdownAll();
}
----

For more information please
link:https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/test/java/com/hazelcast/cluster[check our existing tests^].


'''
**Does Hazelcast support thousands of clients?**

Yes. However, there are some points you should consider.
The environment should be LAN with a high stability and the network speed should be 10 Gbps or higher.
If the number of members is high, the client type should be selected as Unisocket, not Smart Client.
In the case of Smart Clients, since each client opens a connection to the members,
these members should be powerful enough (for example, more cores) to handle hundreds or thousands of connections and client requests.
Also, you should consider using Near Caches in clients to lower the network traffic.
And you should use the Hazelcast releases with the NIO implementation (which starts with Hazelcast 3.2).

Also, you should configure the clients attentively.
See the <<hazelcast-clients, Clients section>> for configuration notes.

'''
**Difference between Lite Member and Smart Client?**

Lite member supports task execution (distributed executor service), smart client does not.
Also, Lite Member is highly coupled with cluster, smart client is not.
Starting with Hazelcast 3.9, you can also promote lite members to data members.
See the <<enabling-lite-members, Lite Members section>> for more information.


'''
**Client-server vs. embedded topologies?**

In the embedded topology, members include both the data and application.
This type of topology is the most useful if your application focuses on high performance computing and many task executions.
Since application is close to data, this topology supports data locality.

In the client-server topology, you create a cluster of members and scale the cluster independently.
Your applications are hosted on the clients and the clients communicate with the members in the cluster to reach data.

Client-server topology fits better if there are multiple applications sharing
the same data or if application deployment is significantly greater than
the cluster size (for example, 500 application servers vs. 10 member cluster).


'''
**Client disconnections during idle time?**

In Hazelcast, socket connections are created with the `SO_KEEPALIVE` option enabled by default.
In most operating systems, default keep-alive time is 2 hours.
If you have a firewall between clients and servers which is configured to reset idle connections/sessions,
make sure that the firewall's idle timeout is greater than the TCP keep-alive defined in the OS.

See link:http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html[Using TCP keepalive under Linux^] and
link:http://technet.microsoft.com/en-us/library/cc957549.aspx[Microsoft TechNet^] for additional information.
