
[[getting-started]]
== Getting Started

This chapter explains how to start a Hazelcast IMDG
cluster and connect a Java client to it.

Please make sure that you have installed Hazelcast IMDG
before proceeding to the following sections. See
link:https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#installing-hazelcast-imdg[Installing Hazelcast IMDG^]
for details.

=== Starting a Hazelcast IMDG Cluster

Hazelcast Java client requires a working Hazelcast
IMDG cluster to run. This cluster handles the storage
and manipulation of the user data, which you can access using
a Java client.

NOTE: Hazelcast offers clients in other languages including
C++, .NET, Node.js, Python, Go and Scala. Please see
link:https://hazelcast.org/clients-languages/[hazelcast.org^]
for their documentation.

There are following options to start a Hazelcast IMDG
cluster easily:

* You can run standalone members by downloading and
running JAR files from the website.
* You can embed members to your Java projects.

We are going to download JARs from the website and
run a standalone member for this section. Follow the
instructions below to start a Hazelcast IMDG cluster:

. Go to Hazelcast's link:https://hazelcast.org/download/#imdg[download page^]
and download either the `.zip` or `.tar` distribution of Hazelcast IMDG.
. Decompress the distribution contents into any directory that
you want to run members from.
. Change into the `/bin` in that directory.
. Use either the `start.sh` or `start.bat` script depending on your
operating system.

Once you run one of the start scripts, you should see the
Hazelcast IMDG logs in the terminal similar to the following:

```
INFO: [192.168.0.3]:5701 [dev] [3.10.4]

Members {size:1, ver:1} [
	Member [192.168.0.3]:5701 - 65dac4d1-2559-44bb-ba2e-ca41c56eedd6 this
]

Sep 06, 2019 10:50:23 AM com.hazelcast.core.LifecycleService
INFO: [192.168.0.3]:5701 [dev] [3.10.4] [192.168.0.3]:5701 is STARTED
```

This means your one-member cluster is started and ready to be used.

=== Example for a Client Connection

As an alternative example to the above cluster initialization,
let's start a two-member Hazelcast IMDG cluster with data structures
and connect a Java client to it:

. The following code starts the first Hazelcast IMDG member and
creates and uses the `customers` map and queue.
+
[source,java]
----
include::{javasource}/GettingStartedMember.java[tag=startmember]
----
+
. Run this `GettingStarted` class a second time to get the second member
started. The members form a cluster and the output is similar to the following.
+
```
Members {size:2, ver:2} [
    Member [127.0.0.1]:5701 - e40081de-056a-4ae5-8ffe-632caf8a6cf1 this
    Member [127.0.0.1]:5702 - 93e82109-16bf-4b16-9c87-f4a6d0873080
]
```
+
Here, you can see the size of your cluster (`size`) and member list
version (`ver`). The member list version is incremented when changes
happen to the cluster, e.g., a member leaving from or joining to the cluster.
+
. Now, add the `hazelcast-client-`*`<version>`*`.jar` library to your classpath.
This is required to use a Hazelcast client.
* The following code starts a Hazelcast Client, connects to our cluster,
and prints the size of the `customers` map.
+
[source,java]
----
public class GettingStartedClient {
    public static void main( String[] args ) {
        ClientConfig clientConfig = new ClientConfig();
        HazelcastInstance client = HazelcastClient.newHazelcastClient( clientConfig );
        IMap map = client.getMap( "customers" );
        System.out.println( "Map Size:" + map.size() );
    }
}
----
+
. When you run it, you see the client properly connecting to the cluster
and printing the map size as **3**.

You can also monitor the client using Hazelcast Management Center. See 
link:https://docs.hazelcast.org/docs/management-center/latest/manual/html/#monitoring-clients[Monitoring Clients^]
for details.